#!/bin/sh
#
# /etc/init.d/candiwrapper
# Subsystem file for "candiwrapper" server

RETVAL=0
prog="CandiWrapper"

start() {
	echo -n $"Starting $prog:"
	RETVAL=$?
	[ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
	echo
}

stop() {
	echo -n $"Stopping $prog:"
	killproc $prog -TERM
	RETVAL=$?
	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
	echo
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status $prog
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|status}"
		RETVAL=1
esac
exit $RETVAL
